### ISSUE TITLE
This is not working for me. Get some write EPIPE error.

### ISSUE THREAD

**Issue by amankapoor** [DeMoorJasper/parcel-plugin-imagemin#12]
```package.json file```
```
.
.
.
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel index.html",
    "build": "parcel build index.html"
  },
.
.
.
```

When I run ```npm run build```, I get the following error, searched a lot but unable to solve.

```
> parcel build index.html

🚨  /home/amankapoor/abc/xyz/urt/assets/FamilyImages/mountain.jpg: Error in file: /home/amankapoor/abc/xyz/urt/assets/FamilyImages/mountain.jpg

write EPIPE

write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:836:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! urt-parcel@1.0.0 build: `parcel build index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the urt-parcel@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amankapoor/.npm/_logs/2018-08-01T15_00_54_093Z-debug.log
```

That log file looks like this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/amankapoor/.nvm/versions/node/v10.7.0/bin/node',
1 verbose cli   '/home/amankapoor/.nvm/versions/node/v10.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v10.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle urt-parcel@1.0.0~prebuild: urt-parcel@1.0.0
6 info lifecycle urt-parcel@1.0.0~build: urt-parcel@1.0.0
7 verbose lifecycle urt-parcel@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle urt-parcel@1.0.0~build: PATH: /home/amankapoor/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/amankapoor/abc/xyz/urt/node_modules/.bin:/home/amankapoor/.nvm/versions/node/v10.7.0/bin:/home/amankapoor/bin:/home/amankapoor/.local/bin:~/flutter/bin:/home/amankapoor/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/snap/bin:/usr/local/go/bin:/bin:~/flutter/bin:/home/amankapoor/go/src:/home/amankapoor/go/bin:/home/amankapoor/Android/Sdk/tools:/home/amankapoor/Android/Sdk/platform-tools
9 verbose lifecycle urt-parcel@1.0.0~build: CWD: /home/amankapoor/abc/xyz/urt
10 silly lifecycle urt-parcel@1.0.0~build: Args: [ '-c', 'parcel build index.html' ]
11 silly lifecycle urt-parcel@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle urt-parcel@1.0.0~build: Failed to exec build script
13 verbose stack Error: urt-parcel@1.0.0 build: `parcel build index.html`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/amankapoor/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/amankapoor/.nvm/versions/node/v10.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid urt-parcel@1.0.0
15 verbose cwd /home/amankapoor/abc/xyz/urt
16 verbose Linux 4.15.0-29-generic
17 verbose argv "/home/amankapoor/.nvm/versions/node/v10.7.0/bin/node" "/home/amankapoor/.nvm/versions/node/v10.7.0/bin/npm" "run" "build"
18 verbose node v10.7.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error urt-parcel@1.0.0 build: `parcel build index.html`
22 error Exit status 1
23 error Failed at the urt-parcel@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

There are many images and on every run on ```npm run build```, the image in the error changes.

**Comment by DeMoorJasper** [comment]
Could you create a reproduction repo with the image? Or is ot copyrighted?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by amankapoor** [comment]
Hi DeMoorJasper,

Well I couldn't do that, so I created a simple react app and loaded one svg, one png and one jpg file using that.

My jpg file was over 6mb, and I got the same issue on that new project. So, I removed that specific jpg file and that error was gone.

Then, I thought maybe size might be was an issue, so instead of downloading a small file, I download a large 16mb file from wikimedia and to my surprise, the thing worked and file was compressed to 900kbs. So basically my image file had some issue. I don't know what kind of issue that is because the jpg files which are blocking my work are taken from my camera.

But in this process, I encountered a new issue also. This new issue is, that when I run my code in development mode WITHOUT ```parcel-plugin-imagemin``` in my ```dependencies``` or ```devDependencies```, my code runs well and I can see the images being rendered. (This is what I did earlier also.)

And, when I add ```parcel-plugin-imagemin``` in my ```dependencies``` or ```devDependencies```, then my code processes, the dist folder gets a compressed image, but I do not see any image rendered in browser. The error I receive is ```Uncaught (in promise) Error: Cannot find module 'assets/camp.jpg'```. This is the link to the repo (https://github.com/amankapoor/parcel-images) and you can try running it by installing ```parcel-plugin-imagemin``` and uninstalling ```parcel-plugin-imagemin```, you would be able to reproduce the issue.

Also, I have added my camera's image in the repo. It is ```assets/realCamp.JPG```. If you uncomment line 3 and line 10 in ```main.js``` file, then you would receive an error like following: 

```
amankapoor@amankapoor:~/parcel-images$ npm run build

> parcel-images@1.0.0 build /home/amankapoor/parcel-images
> parcel build index.html

🚨  /home/amankapoor/parcel-images/assets/realCamp.JPG: Error in file: /home/amankapoor/parcel-images/assets/realCamp.JPG

read ECONNRESET

read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:615:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! parcel-images@1.0.0 build: `parcel build index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parcel-images@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amankapoor/.npm/_logs/2018-08-01T19_31_27_431Z-debug.log
```
on my original repo, I received write EPIPE error and in this repo I receive this ECONNRESET error.

The log looks like this, in case you need it,
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/amankapoor/.nvm/versions/node/v8.9.4/bin/node',
1 verbose cli   '/home/amankapoor/.nvm/versions/node/v8.9.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle parcel-images@1.0.0~prebuild: parcel-images@1.0.0
6 info lifecycle parcel-images@1.0.0~build: parcel-images@1.0.0
7 verbose lifecycle parcel-images@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle parcel-images@1.0.0~build: PATH: /home/amankapoor/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/amankapoor/parcel-images/node_modules/.bin:/home/amankapoor/.nvm/versions/node/v8.9.4/bin:/home/amankapoor/bin:/home/amankapoor/.local/bin:~/flutter/bin:/home/amankapoor/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/snap/bin:/usr/local/go/bin:/bin:~/flutter/bin:/home/amankapoor/go/src:/home/amankapoor/go/bin:/home/amankapoor/Android/Sdk/tools:/home/amankapoor/Android/Sdk/platform-tools
9 verbose lifecycle parcel-images@1.0.0~build: CWD: /home/amankapoor/parcel-images
10 silly lifecycle parcel-images@1.0.0~build: Args: [ '-c', 'parcel build index.html' ]
11 silly lifecycle parcel-images@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle parcel-images@1.0.0~build: Failed to exec build script
13 verbose stack Error: parcel-images@1.0.0 build: `parcel build index.html`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/amankapoor/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/amankapoor/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid parcel-images@1.0.0
15 verbose cwd /home/amankapoor/parcel-images
16 verbose Linux 4.15.0-29-generic
17 verbose argv "/home/amankapoor/.nvm/versions/node/v8.9.4/bin/node" "/home/amankapoor/.nvm/versions/node/v8.9.4/bin/npm" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error parcel-images@1.0.0 build: `parcel build index.html`
22 error Exit status 1
23 error Failed at the parcel-images@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

So, that's my problem now. I think my camera images are problematic and that's why I am receiving those EPIPE and ECONNRESET errors. They are just few so I can manually compress them in my project if I don't find a solution, but in case you know what could be causing it, then please let know. I would love to learn this case.

And the second error, which is now the primary error of this github issue, is that, if I add ```parcel-plugin-imagemin``` package, then I get module not found error as described above. Also, you will discover that after adding this plugin, the output jpg file in dist folder will be like [parentFolderName].[hash].jpg instead of [originalFileName].[hash].jpg

Thank You.

**Comment by DeMoorJasper** [comment]
Sorry for the long delay on my response. The naming is done by Parcel, this plugin has nothing to do with the naming of bundles/files.

About the EPIPE error, I don't think this has anything to do with my plugin either. I'm not able to reproduce, would help if I could get my hands on one of those failing images.

Perhaps you can have a look if something similar exists in the `imagemin-mozjpeg` repository

**Comment by luisrudge** [comment]
@DeMoorJasper found the issue: https://github.com/imagemin/imagemin-mozjpeg/issues/28#issuecomment-397825824

maybe you can downgrade the dependency until this gets figured it out?
